#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace iobserve.Data	
{
	public partial class Caption
	{
		private string _id;
		public virtual string Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _label_id;
		public virtual string Label_id
		{
			get
			{
				return this._label_id;
			}
			set
			{
				this._label_id = value;
			}
		}
		
		private string _language_code;
		public virtual string Language_code
		{
			get
			{
				return this._language_code;
			}
			set
			{
				this._language_code = value;
			}
		}
		
		private string _label_text;
		public virtual string Label_text
		{
			get
			{
				return this._label_text;
			}
			set
			{
				this._label_text = value;
			}
		}
		
		private string _label_description;
		public virtual string Label_description
		{
			get
			{
				return this._label_description;
			}
			set
			{
				this._label_description = value;
			}
		}
		
		private string _remarks;
		public virtual string Remarks
		{
			get
			{
				return this._remarks;
			}
			set
			{
				this._remarks = value;
			}
		}
		
		private DateTimeOffset ___createdat;
		public virtual DateTimeOffset __createdat
		{
			get
			{
				return this.___createdat;
			}
			set
			{
				this.___createdat = value;
			}
		}
		
		private DateTimeOffset ___updatedat;
		public virtual DateTimeOffset __updatedat
		{
			get
			{
				return this.___updatedat;
			}
			set
			{
				this.___updatedat = value;
			}
		}
		
		private string _tablecol;
		public virtual string Tablecol
		{
			get
			{
				return this._tablecol;
			}
			set
			{
				this._tablecol = value;
			}
		}
		
		private string _master_caption;
		public virtual string Master_caption
		{
			get
			{
				return this._master_caption;
			}
			set
			{
				this._master_caption = value;
			}
		}
		
	}
}
#pragma warning restore 1591
