#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace iobserve.Data	
{
	public partial class Report
	{
		private string _id;
		public virtual string Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DateTimeOffset ___createdAt;
		public virtual DateTimeOffset __createdAt
		{
			get
			{
				return this.___createdAt;
			}
			set
			{
				this.___createdAt = value;
			}
		}
		
		private System.Nullable<System.DateTimeOffset> ___updatedAt;
		public virtual System.Nullable<System.DateTimeOffset> __updatedAt
		{
			get
			{
				return this.___updatedAt;
			}
			set
			{
				this.___updatedAt = value;
			}
		}
		
		private long ___version;
		public virtual long __version
		{
			get
			{
				return this.___version;
			}
			set
			{
				this.___version = value;
			}
		}
		
		private string _media_video_id;
		public virtual string Media_video_id
		{
			get
			{
				return this._media_video_id;
			}
			set
			{
				this._media_video_id = value;
			}
		}
		
		private string _followuprequired;
		public virtual string Followuprequired
		{
			get
			{
				return this._followuprequired;
			}
			set
			{
				this._followuprequired = value;
			}
		}
		
		private string _location;
		public virtual string Location
		{
			get
			{
				return this._location;
			}
			set
			{
				this._location = value;
			}
		}
		
		private string _risklevel;
		public virtual string Risklevel
		{
			get
			{
				return this._risklevel;
			}
			set
			{
				this._risklevel = value;
			}
		}
		
		private string _remarks;
		public virtual string Remarks
		{
			get
			{
				return this._remarks;
			}
			set
			{
				this._remarks = value;
			}
		}
		
		private string _lng;
		public virtual string Lng
		{
			get
			{
				return this._lng;
			}
			set
			{
				this._lng = value;
			}
		}
		
		private string _media_audio_id;
		public virtual string Media_audio_id
		{
			get
			{
				return this._media_audio_id;
			}
			set
			{
				this._media_audio_id = value;
			}
		}
		
		private string _status_label_id;
		public virtual string Status_label_id
		{
			get
			{
				return this._status_label_id;
			}
			set
			{
				this._status_label_id = value;
			}
		}
		
		private string _customer;
		public virtual string Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
		}
		
		private string _location_scenario_id;
		public virtual string Location_scenario_id
		{
			get
			{
				return this._location_scenario_id;
			}
			set
			{
				this._location_scenario_id = value;
			}
		}
		
		private string _hazardeliminated;
		public virtual string Hazardeliminated
		{
			get
			{
				return this._hazardeliminated;
			}
			set
			{
				this._hazardeliminated = value;
			}
		}
		
		private string _supnotified;
		public virtual string Supnotified
		{
			get
			{
				return this._supnotified;
			}
			set
			{
				this._supnotified = value;
			}
		}
		
		private string _observer_id;
		public virtual string Observer_id
		{
			get
			{
				return this._observer_id;
			}
			set
			{
				this._observer_id = value;
			}
		}
		
		private string _actiontaken;
		public virtual string Actiontaken
		{
			get
			{
				return this._actiontaken;
			}
			set
			{
				this._actiontaken = value;
			}
		}
		
		private string _response_array;
		public virtual string Response_array
		{
			get
			{
				return this._response_array;
			}
			set
			{
				this._response_array = value;
			}
		}
		
		private string _media_picture_id;
		public virtual string Media_picture_id
		{
			get
			{
				return this._media_picture_id;
			}
			set
			{
				this._media_picture_id = value;
			}
		}
		
		private string _lat;
		public virtual string Lat
		{
			get
			{
				return this._lat;
			}
			set
			{
				this._lat = value;
			}
		}
		
		private string _workstopped;
		public virtual string Workstopped
		{
			get
			{
				return this._workstopped;
			}
			set
			{
				this._workstopped = value;
			}
		}
		
		private System.Nullable<System.DateTimeOffset> _observation_date;
		public virtual System.Nullable<System.DateTimeOffset> Observation_date
		{
			get
			{
				return this._observation_date;
			}
			set
			{
				this._observation_date = value;
			}
		}
		
		private string _notes;
		public virtual string Notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				this._notes = value;
			}
		}
		
		private string _media_signature;
		public virtual string Media_signature
		{
			get
			{
				return this._media_signature;
			}
			set
			{
				this._media_signature = value;
			}
		}
		
		private string _feedback;
		public virtual string Feedback
		{
			get
			{
				return this._feedback;
			}
			set
			{
				this._feedback = value;
			}
		}
		
	}
}
#pragma warning restore 1591
