#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace iobserve.Data	
{
	public partial class V_location
	{
		private string _qr_id;
		public virtual string Qr_id
		{
			get
			{
				return this._qr_id;
			}
			set
			{
				this._qr_id = value;
			}
		}
		
		private string _location_zipcode;
		public virtual string Location_zipcode
		{
			get
			{
				return this._location_zipcode;
			}
			set
			{
				this._location_zipcode = value;
			}
		}
		
		private string _location_state;
		public virtual string Location_state
		{
			get
			{
				return this._location_state;
			}
			set
			{
				this._location_state = value;
			}
		}
		
		private string _location_name;
		public virtual string Location_name
		{
			get
			{
				return this._location_name;
			}
			set
			{
				this._location_name = value;
			}
		}
		
		private string _location_lng;
		public virtual string Location_lng
		{
			get
			{
				return this._location_lng;
			}
			set
			{
				this._location_lng = value;
			}
		}
		
		private string _location_lat;
		public virtual string Location_lat
		{
			get
			{
				return this._location_lat;
			}
			set
			{
				this._location_lat = value;
			}
		}
		
		private string _location_country;
		public virtual string Location_country
		{
			get
			{
				return this._location_country;
			}
			set
			{
				this._location_country = value;
			}
		}
		
		private string _location_city;
		public virtual string Location_city
		{
			get
			{
				return this._location_city;
			}
			set
			{
				this._location_city = value;
			}
		}
		
		private string _location_address2;
		public virtual string Location_address2
		{
			get
			{
				return this._location_address2;
			}
			set
			{
				this._location_address2 = value;
			}
		}
		
		private string _location_address1;
		public virtual string Location_address1
		{
			get
			{
				return this._location_address1;
			}
			set
			{
				this._location_address1 = value;
			}
		}
		
		private string _language_code;
		public virtual string Language_code
		{
			get
			{
				return this._language_code;
			}
			set
			{
				this._language_code = value;
			}
		}
		
		private string _id;
		public virtual string Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _erp_location_id;
		public virtual string Erp_location_id
		{
			get
			{
				return this._erp_location_id;
			}
			set
			{
				this._erp_location_id = value;
			}
		}
		
		private string _default_scenario_id;
		public virtual string Default_scenario_id
		{
			get
			{
				return this._default_scenario_id;
			}
			set
			{
				this._default_scenario_id = value;
			}
		}
		
		private string _default_scenario;
		public virtual string Default_scenario
		{
			get
			{
				return this._default_scenario;
			}
			set
			{
				this._default_scenario = value;
			}
		}
		
		private string _company_name;
		public virtual string Company_name
		{
			get
			{
				return this._company_name;
			}
			set
			{
				this._company_name = value;
			}
		}
		
		private string _company_id;
		public virtual string Company_id
		{
			get
			{
				return this._company_id;
			}
			set
			{
				this._company_id = value;
			}
		}
		
		private string _admin_phone;
		public virtual string Admin_phone
		{
			get
			{
				return this._admin_phone;
			}
			set
			{
				this._admin_phone = value;
			}
		}
		
		private string _admin_name;
		public virtual string Admin_name
		{
			get
			{
				return this._admin_name;
			}
			set
			{
				this._admin_name = value;
			}
		}
		
		private string _admin_email;
		public virtual string Admin_email
		{
			get
			{
				return this._admin_email;
			}
			set
			{
				this._admin_email = value;
			}
		}
		
	}
}
#pragma warning restore 1591
